name: Pytest

on:
  push:
    branches:
      - '**'    
  pull_request:
    branches:
      - '**'    

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up environment variables from secrets
        run: echo "Environment variables set!"
        env:
          API_URL: ${{ secrets.SUPABASE_URL }}
          API_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Run tests
        run: |
          cd backend
          pytest --maxfail=1 --disable-warnings -v
